/**
 * @fileOverview Stores constants and template strings used for generating representative emails.
 * Includes variations for tone, action, rationale, and structure.
 */

import type { SelectedItem } from '@/services/tax-spending'; // Import necessary types

// --- Tone Buckets ---
export type Tone = 0 | 1 | 2 | 3; // 0: Polite, 1: Concerned, 2: Stern, 3: Angry

// --- Email Components ---

// SUBJECT Lines
export const SUBJECT: Record<Tone, string> = {
  0: "A Constituent's Perspective on Federal Budget Priorities",
  1: "Concerns Regarding Specific Federal Spending Allocations",
  2: "Urgent Request: Reevaluate Federal Budget Priorities and Debt",
  3: "Demand for Immediate Action: Federal Spending & Fiscal Responsibility",
};

// OPENING Paragraphs
export const OPENING: Record<Tone, (loc: string) => string> = {
  0: loc => `I hope this message finds you well. As a concerned constituent residing in ${loc || '[Your Area]'}, I am writing to respectfully share my perspective on the current allocation of federal tax dollars. I believe thoughtful discussion about these priorities is essential for effective governance.`,
  1: loc => `I am writing to you today as a constituent from ${loc || '[Your Area]'} with growing concerns about federal spending patterns. Analyzing how our tax money is distributed raises important questions about efficiency, necessity, and alignment with our community's values.`,
  2: loc => `Representing constituents like myself in ${loc || '[Your Area]'}, I must register my strong dissatisfaction with the current trajectory of federal spending. It is imperative that these priorities undergo immediate and serious reevaluation to ensure taxpayer money serves the public good effectively.`,
  3: loc => `From ${loc || '[Your Area]'}, I am compelled to demand immediate and decisive action regarding the federal budget. The current pattern of spending, marked by questionable priorities and apparent waste, is fiscally irresponsible and requires your urgent intervention.`,
};

// INTRODUCTIONS to the list of items (More variety)
export const LIST_INTRO: Record<Tone, string[]> = {
  0: [
    "After reviewing estimates of how federal funds are spent, I wanted to highlight a few areas that I believe warrant closer examination:",
    "Reflecting on our budget priorities, several specific funding allocations stand out to me:",
    "My review of the federal spending breakdown brings the following items to my attention:",
    "Regarding the current budget, I'd like to offer my perspective on the following specific areas:",
    "Several aspects of the federal budget allocation deserve discussion, including:",
    "Considering the federal budget, the following points are particularly salient:",
  ],
  1: [
    "My analysis of the budget breakdown reveals several specific items that cause me significant concern and which I urge you to address:",
    "Looking at where our tax dollars go, I am particularly troubled by the funding levels for the following programs:",
    "The following expenditures raise serious questions and demand your attention:",
    "I am writing to express concern about the following specific budget allocations:",
    "Certain spending priorities reflected in the budget warrant scrutiny, notably:",
    "Several budget items require closer examination due to potential inefficiencies or misalignment with priorities:",
  ],
  2: [
    "Based on current spending levels, the following programs stand out as demanding significant reassessment and potential correction:",
    "Several areas of the federal budget appear deeply problematic and require immediate attention:",
    "It is difficult to justify the current funding for these specific items, which need urgent review:",
    "The following spending decisions are particularly concerning and require your prompt review:",
    "I must insist on a reevaluation of funding for the following items:",
    "The current allocation for these programs raises serious questions about fiscal prudence:",
  ],
  3: [
    "Below are some of the most glaring examples of what I perceive as misguided priorities and wasteful spending requiring your direct action:",
    "The following expenditures represent unacceptable uses of taxpayer funds and must be addressed immediately:",
    "These specific funding decisions exemplify the fiscal irresponsibility I am demanding you correct:",
    "The current allocation for these items is deeply flawed and requires immediate reform:",
    "I demand action on the following examples of wasteful or misguided spending:",
    "The lack of fiscal discipline is evident in the funding of these programs:",
  ]
};

// ACTION Phrases (indexed by fundingLevel + tone bucket) - Refined for grammatical correctness as clauses or sentences.
// These should integrate smoothly after an ITEM_OPENER.
export const ACTION_PHRASES: Record<SelectedItem['fundingLevel'], [string, string, string, string]> = {
    [-2]: [ // Slash Heavily
        "should be considered for significant reduction or phasing out", // Clause
        "requires a substantial cut, as its current funding seems excessive", // Clause
        "must be drastically scaled back; this expenditure is difficult to justify.", // Sentence
        "must be eliminated or fundamentally reformed; this spending is unacceptable.", // Sentence
    ],
    [-1]: [ // Cut Significantly
        "could likely be reduced without compromising essential functions", // Clause
        "should undergo significant cuts, given clear opportunities for savings", // Clause
        "demands a sharp reduction to better align with fiscal responsibility", // Clause
        "needs an aggressive cut; taxpayers expect more prudent use of funds.", // Sentence
    ],
    [0]: [ // Improve Efficiency / Maintain with Oversight
        "should be maintained, but with a strong emphasis on efficiency and accountability", // Clause
        "could continue at current levels, provided there's rigorous oversight", // Clause
        "funding might remain level, but only if waste is eliminated and performance metrics are met", // Clause
        "is questionable but acceptable only with strict audits and proven results.", // Sentence
    ],
    [1]: [ // Fund / Modest Increase
        "deserves stable and perhaps modestly increased funding", // Clause
        "should receive reliable support, potentially with a moderate increase", // Clause
        "warrants a noticeable funding boost to strengthen its capabilities", // Clause
        "requires a clear increase in resources to adequately address important needs.", // Sentence
    ],
    [2]: [ // Fund More / Substantial Increase
        "merits a substantial increase in funding, as potential benefits are significant", // Clause
        "needs robust new investment to expand its positive impact", // Clause
        "should be prioritized for major funding growth to address critical challenges", // Clause
        "demands urgent and considerable expansion; underfunding this is shortsighted.", // Sentence
    ]
};


// RATIONALE Snippets (indexed by item.id + fundingLevel rationale type)
export type FundingActionRationale = 'cut' | 'review' | 'fund';

// Keys: `${item.id}_${FundingActionRationale}` (e.g., 'medicaid_cut', 'nih_fund', 'pentagon_review')
// Ensure rationales are complete clauses or sentences that make sense following a connector.
export const SPECIFIC_RATIONALES: Record<string, string[]> = {
    // --- Health ---
    medicaid_cut: [
        "exploring reforms to enhance Medicaid's long-term fiscal sustainability is crucial.",
        "targeting Medicaid resources more effectively towards core health services could improve efficiency.",
        "Medicaid's growth necessitates exploring ways to control costs responsibly.",
        "ensuring state and federal Medicaid funds are used with maximum efficiency should be a constant goal.",
        "we must find ways to manage the rising costs of Medicaid without harming beneficiaries.",
        "potential savings could be achieved by improving coordination between Medicaid and Medicare.",
    ],
    medicaid_fund: [
        "expanding Medicaid eligibility remains a powerful tool for improving health outcomes.",
        "robust Medicaid funding is essential for covering vulnerable populations.",
        "investing adequately in Medicaid strengthens community health infrastructure.",
        "ensuring fair reimbursement rates within Medicaid helps maintain access to providers.",
        "Medicaid is a lifeline for millions; cutting it would have devastating consequences.",
        "strengthening Medicaid's support for long-term care services is crucial.",
    ],
    medicaid_review: [
        "implementing stronger measures to prevent fraud, waste, and abuse within Medicaid protects taxpayer dollars.",
        "continuously evaluating Medicaid delivery models for efficiency and effectiveness is key.",
        "focusing Medicaid resources on high-value care and preventative services leads to better outcomes.",
        "streamlining Medicaid administration could reduce overhead.",
        "improving data analysis can help identify areas for efficiency improvements within Medicaid.",
        "enhancing transparency in state Medicaid programs ensures accountability.",
    ],
    medicare_cut: [
        "addressing Medicare's long-term solvency requires exploring options like negotiating drug prices.",
        "implementing reforms to improve Medicare's cost-effectiveness is vital for its future.",
        "careful scrutiny of Medicare spending can prevent unnecessary procedures.",
        "promoting efficiency within the Medicare system is necessary given demographic pressures.",
        "serious discussions about Medicare reform are needed to ensure its viability.",
        "limiting certain supplemental benefits or increasing premiums for higher-income beneficiaries could be considered.",
    ],
    medicare_fund: [
        "guaranteeing reliable healthcare for seniors through a strong Medicare program is a fundamental commitment.",
        "strengthening Medicare, potentially by adding benefits, improves seniors' quality of life.",
        "adequate Medicare funding is critical for the health and financial security of older Americans.",
        "ensuring Medicare can negotiate drug prices effectively would lower costs significantly.",
        "Medicare is a promise we must keep to our seniors.",
        "investing in Medicare's ability to cover preventative services saves money long-term.",
    ],
    medicare_review: [
        "combating fraud and abuse within the Medicare system must remain a top priority.",
        "ongoing evaluation of Medicare payment systems is needed to incentivize high-quality care.",
        "promoting value-based care models within Medicare can lead to better outcomes.",
        "simplifying Medicare enrollment and navigation would benefit beneficiaries.",
        "enhancing Medicare's ability to detect and prevent payment errors saves significant sums.",
        "improving the coordination of care for Medicare beneficiaries with chronic conditions is necessary.",
    ],
    nih_cut: [
        "NIH funding should prioritize research with the highest potential public health impact.",
        "ensuring NIH grants avoid duplication and target truly innovative science is fiscally prudent.",
        "streamlining NIH grant administration could maximize the research impact of taxpayer dollars.",
        "balancing NIH funding with other national priorities requires careful consideration.",
        "not all NIH-funded research yields tangible benefits; tighter focus is needed.",
        "greater emphasis on translating research findings into practical applications could improve return on investment.",
    ],
    nih_fund: [
        "investing boldly in the National Institutes of Health accelerates medical breakthroughs.",
        "increased NIH funding is essential for tackling devastating diseases.",
        "supporting basic science research through the NIH provides the foundation for future cures.",
        "NIH funding drives innovation, creates high-tech jobs, and yields economic benefits.",
        "medical progress depends heavily on consistent and robust NIH funding.",
        "NIH research leads to longer, healthier lives and reduces overall healthcare costs.",
    ],
    nih_review: [
        "refining the NIH grant review process ensures fairness and supports the most promising research.",
        "fostering greater collaboration and data sharing facilitated by the NIH can speed up progress.",
        "directing NIH resources towards addressing health disparities promotes health equity.",
        "ensuring transparency and accountability in how NIH funds are utilized is paramount.",
        "improving the efficiency of clinical trials supported by the NIH is needed.",
        "encouraging more research into prevention and public health interventions is valuable.",
    ],
    cdc_cut: [
        "focusing CDC resources tightly on core functions like disease surveillance is essential.",
        "evaluating the effectiveness of all CDC programs ensures taxpayer money yields tangible benefits.",
        "streamlining CDC operations and reducing administrative overhead could enhance efficiency.",
        "ensuring CDC activities do not overlap unnecessarily with state or local efforts is key.",
        "the CDC's budget warrants review for potential savings.",
        "certain CDC functions could potentially be handled by other agencies.",
    ],
    cdc_fund: [
        "a fully funded CDC is paramount for national security and pandemic preparedness.",
        "investing in the CDC's data systems, labs, and workforce strengthens disease control.",
        "supporting the CDC's global health security efforts helps contain threats abroad.",
        "adequate CDC funding ensures timely and reliable public health guidance.",
        "pandemic prevention and response require a strong, well-resourced CDC.",
        "CDC funding is critical for addressing chronic diseases and environmental health threats.",
    ],
    cdc_review: [
        "improving the clarity and timeliness of CDC guidance during emergencies builds trust.",
        "enhancing CDC communication strategies and transparency is vital.",
        "ensuring the CDC maintains scientific integrity and avoids politicization is crucial.",
        "strengthening partnerships between the CDC and state/local agencies improves coordination.",
        "modernizing the CDC's data infrastructure is essential for effective surveillance.",
        "evaluating the CDC's preparedness for future public health crises is necessary.",
    ],
    substance_mental_health_cut: [
        "funding for mental health programs must prioritize evidence-based treatments.",
        "careful evaluation is needed to avoid duplication between mental health initiatives.",
        "targeting resources towards programs demonstrably reducing overdoses is crucial.",
        "ensuring fiscal accountability within substance use and mental health grants is needed.",
        "these programs require scrutiny to ensure they are achieving results.",
        "consolidating various grant programs could improve efficiency.",
    ],
    substance_mental_health_fund: [
        "addressing the nation's mental health and addiction crises requires increased investment.",
        "expanding access to affordable mental healthcare and substance use disorder services is essential.",
        "investing in the behavioral health workforce and integrating care are critical.",
        "supporting crisis response systems like the 988 hotline requires adequate resources.",
        "the human and economic costs of untreated mental illness and addiction are immense.",
        "investing in prevention programs saves lives and reduces future costs.",
    ],
    substance_mental_health_review: [
        "improving coordination among agencies involved in mental health is key.",
        "enforcing mental health parity laws ensures equitable insurance coverage.",
        "evaluating the effectiveness of different treatment models helps optimize fund use.",
        "reducing stigma associated with seeking mental health treatment requires ongoing effort.",
        "enhancing data collection on treatment outcomes is important.",
        "integrating mental health services into primary care settings improves access.",
    ],
     // --- War and Weapons ---
    pentagon_cut: [
        "the immense Pentagon budget demands significant reduction, focusing on genuine defense needs.",
        "a thorough audit of Pentagon spending is essential to identify inefficiencies.",
        "shifting funds from unproven weapons systems towards readiness could be more effective.",
        "reducing the Pentagon's budget would free up critical resources for domestic needs.",
        "U.S. military spending dwarfs that of other nations; reductions are feasible.",
        "ending wasteful Pentagon accounting practices is long overdue.",
    ],
    pentagon_fund: [
        "maintaining a strong national defense requires sufficient funding for personnel and modernization.",
        "investing in advanced military capabilities is necessary to deter adversaries.",
        "ensuring our troops have the best equipment and support is vital.",
        "predictable defense funding enhances strategic planning and readiness.",
        "military readiness requires sustained investment in training and maintenance.",
        "modernizing our forces is crucial to keep pace with potential adversaries.",
    ],
    pentagon_review: [
        "rigorous oversight of Pentagon spending is crucial to prevent waste and fraud.",
        "reforming the Pentagon's acquisition process is needed to control costs.",
        "regularly reassessing strategic priorities ensures the military is optimized for current threats.",
        "improving transparency and accountability in all defense spending is paramount.",
        "the Pentagon has failed multiple audits; this requires serious corrective action.",
        "strengthening whistleblower protections within the DoD encourages accountability.",
    ],
    pentagon_contractors_cut: [
        "over-reliance on expensive defense contractors inflates costs and requires stricter oversight.",
        "billions could be saved by bringing more functions currently performed by contractors back in-house.",
        "requiring more competition and fixed-price contracts for defense services protects taxpayers.",
        "the revolving door between the Pentagon and defense contractors warrants scrutiny.",
        "contractor profits should not come at the expense of national security.",
        "reducing dependence on contractors enhances government accountability.",
    ],
     pentagon_contractors_review: [
        "enhancing transparency in defense contracting, including performance data, is essential.",
        "implementing stronger mechanisms to prevent waste in defense contracts.",
        "evaluating the cost-effectiveness of outsourcing versus using government personnel.",
        "ensuring contractor performance meets rigorous standards.",
        "improving oversight of contractor billing and performance metrics.",
        "limiting the use of contractors for inherently governmental functions.",
    ],
    pentagon_personnel_cut: [
        "reviewing personnel costs for efficiencies in areas like healthcare administration is possible.",
        "optimizing military force structure could potentially yield savings.",
        "balancing personnel compensation with investments in training requires careful management.",
        "evaluating the cost-effectiveness of current military healthcare systems.",
        "streamlining military bureaucracy could reduce personnel costs.",
    ],
    pentagon_personnel_fund: [
        "attracting skilled military personnel necessitates competitive pay and benefits.",
        "investing in the well-being and readiness of service members is crucial.",
        "adequate funding for personnel accounts directly impacts morale and retention.",
        "ensuring high-quality healthcare and housing for military families is necessary.",
        "providing robust mental health support for service members is critical.",
        "competitive compensation is essential to recruit top talent.",
    ],
    pentagon_personnel_review: [
        "regularly reviewing military compensation packages to ensure competitiveness.",
        "improving access to quality healthcare and childcare for military families.",
        "streamlining personnel management processes reduces administrative burdens.",
        "focusing on programs that genuinely support service member well-being.",
        "addressing issues like military spouse unemployment.",
        "ensuring accountability for preventing issues like sexual assault.",
    ],
    pentagon_top5_contractors_cut: [
        "the heavy concentration of defense contracts among a few large firms warrants action.",
        "reducing the share of contracts flowing to the top 5 corporations could foster competition.",
        "increased scrutiny is needed on contracts awarded to the largest firms.",
        "breaking up the excessive influence of the largest contractors is necessary.",
        "promoting competition leads to better prices and innovation.",
        "questioning no-bid contracts awarded to major firms.",
    ],
    pentagon_top5_contractors_review: [
        "the relationship between the Pentagon and its largest contractors needs close oversight.",
        "evaluating the strategic risks of relying heavily on a small number of firms.",
        "promoting opportunities for smaller, innovative companies is needed.",
        "ensuring mergers among large contractors do not further reduce competition.",
        "demanding greater transparency on the performance of major programs.",
        "investigating potential conflicts of interest involving former officials.",
    ],
    nuclear_weapons_cut: [
        "the exorbitant cost of maintaining and modernizing the nuclear arsenal should be sharply curtailed.",
        "reducing reliance on nuclear weapons could save billions.",
        "questioning the necessity of specific, costly nuclear modernization programs.",
        "shifting resources from nuclear weapons to conventional deterrence is possible.",
        "the risks associated with nuclear weapons often outweigh perceived benefits.",
        "investing in diplomacy is a better path to security.",
    ],
    nuclear_weapons_fund: [
        "modernizing the nuclear triad is essential for strategic deterrence.",
        "ensuring the safety and reliability of the existing stockpile requires investment.",
        "maintaining a credible nuclear deterrent is vital as long as others possess these weapons.",
        "funding for non-proliferation efforts is also critical.",
    ],
    nuclear_weapons_review: [
        "the long-term costs of nuclear modernization require rigorous review.",
        "ensuring robust command, control, and safety measures for the arsenal is necessary.",
        "balancing investments in nuclear deterrence with conventional forces.",
        "pursuing arms control negotiations to reduce nuclear risks.",
        "improving transparency regarding the costs of the nuclear arsenal.",
        "investing in verification technologies for arms control treaties.",
    ],
    foreign_military_aid_cut: [
        "U.S. foreign military aid often fuels conflicts and should be sharply reduced.",
        "providing weapons abroad can entangle the U.S. in foreign disputes.",
        "reallocating funds from military aid to diplomacy would be wiser.",
        "conditioning all military aid strictly on human rights is necessary.",
        "military aid should not subsidize wealthy nations.",
        "focusing on humanitarian aid rather than weapons transfers is preferable.",
    ],
    foreign_military_aid_fund: [
        "strategic foreign military aid can strengthen key allies.",
        "security assistance helps partner nations counter shared threats.",
        "military aid can be a tool to build relationships.",
        "providing equipment and training improves partner capabilities.",
    ],
    foreign_military_aid_review: [
        "all foreign military aid must be subject to strict human rights conditions.",
        "the effectiveness of each military aid package requires evaluation.",
        "transparency regarding the uses of U.S. military aid is essential.",
        "balancing military aid with diplomatic and economic tools.",
        "ensuring aid does not contribute to internal repression.",
        "improving end-use monitoring of U.S.-provided weapons.",
    ],
    israel_wars_cut: [
        "unconditional military aid to nations like Israel drains U.S. resources.",
        "the level of military funding provided to Israel warrants scrutiny.",
        "conditioning military aid to Israel on compliance with international law is necessary.",
        "reassessing the strategic benefits versus the costs of extensive aid to Israel.",
        "providing massive military aid without accountability undermines U.S. values.",
        "linking aid to progress towards peaceful conflict resolution.",
    ],
     israel_wars_fund: [
        "supporting Israel's security through military aid is a key U.S. policy pillar.",
        "funding for systems like Iron Dome enhances Israeli defense.",
        "security assistance to Israel is mutually beneficial for intelligence sharing.",
        "maintaining Israel's qualitative military edge is a U.S. commitment.",
    ],
     israel_wars_review: [
        "the impact of U.S. aid to Israel on regional stability requires assessment.",
        "transparency regarding the specific uses of U.S. military aid by Israel is crucial.",
        "balancing the partnership with Israel against broader U.S. interests.",
        "ensuring U.S.-provided weapons are used in accordance with international law.",
        "evaluating whether current aid levels best serve long-term peace.",
        "considering the humanitarian impact of conflicts involving U.S.-funded weapons.",
    ],
    f35_cut: [
        "the F-35 program's staggering cost overruns warrant significant funding cuts.",
        "reducing the total number of F-35s procured could save billions.",
        "continuing massive funding for the F-35 without addressing affordability is irresponsible.",
        "exploring more cost-effective aircraft alternatives is necessary.",
        "the F-35's high operating costs strain the budget.",
        "halting procurement until critical deficiencies are resolved.",
    ],
    f35_review: [
        "rigorous testing of the F-35's performance and maintenance costs is crucial.",
        "holding Lockheed Martin accountable for meeting F-35 cost targets.",
        "ensuring the F-35 program delivers promised capabilities at an acceptable cost.",
        "considering the long-term sustainment costs of the F-35 fleet.",
        "improving the reliability and availability rates of the F-35.",
        "addressing software development challenges and cybersecurity vulnerabilities.",
    ],
    pentagon_spacex_cut: [
        "Pentagon contracts with profitable companies like SpaceX need stronger justification.",
        "ensuring fair competition in national security space launches is essential.",
        "questioning the need to subsidize established commercial space ventures.",
        "demanding greater transparency on Pentagon-SpaceX contracts.",
        "taxpayers should not fund routine launch services for established companies.",
        "promoting a diverse launch market prevents monopolies.",
    ],
    pentagon_spacex_review: [
        "contracts awarded to SpaceX require robust oversight for performance and cost control.",
        "transparency regarding the terms of Pentagon contracts with commercial space companies.",
        "assessing the long-term strategy for utilizing commercial partners for space missions.",
        "ensuring competition is maintained in the national security launch market.",
        "evaluating the resilience of commercial launch services for defense payloads.",
        "managing potential conflicts between commercial interests and national security.",
    ],
    pentagon_dei_cut: [
        "funding for Pentagon DEI initiatives should be evaluated for effectiveness.",
        "resources allocated to DEI programs must be justified based on clear outcomes.",
        "ensuring DEI efforts focus on equal opportunity and merit.",
        "preventing DEI programs from becoming overly bureaucratic.",
        "DEI initiatives should not lower standards or compromise effectiveness.",
        "questioning the cost of certain mandatory DEI trainings.",
    ],
    pentagon_dei_fund: [
        "well-implemented DEI initiatives can enhance military readiness by attracting diverse talent.",
        "promoting an inclusive environment strengthens the Armed Forces.",
        "addressing discrimination through DEI programs contributes to unit cohesion.",
        "a military that reflects the nation it defends is stronger.",
    ],
    pentagon_dei_review: [
        "the goals and costs of Pentagon DEI programs require clear definition.",
        "ensuring DEI training is evidence-based and contributes to effectiveness.",
        "balancing DEI goals with the military's primary mission.",
        "guaranteeing DEI initiatives uphold principles of meritocracy.",
        "evaluating the impact of DEI programs on recruitment and morale.",
        "ensuring DEI efforts are integrated effectively into military culture.",
    ],
    // --- Veterans ---
    va_cut: [
        "the VA system needs continuous efforts to improve efficiency.",
        "modernizing VA operations and IT systems could focus resources on care.",
        "ensuring accountability and eliminating wasteful spending within the VA is necessary.",
        "streamlining VA service delivery without compromising quality.",
        "reducing administrative overhead at the VA is essential.",
        "better integration with community care options might offer savings.",
    ],
    va_fund: [
        "fulfilling our promise to veterans requires robust funding for VA healthcare.",
        "investing in the VA system, including expanding access, meets veterans' needs.",
        "adequate funding for VA benefits like the GI Bill helps veterans thrive.",
        "supporting VA research contributes to advancements in veteran healthcare.",
        "we have a sacred obligation to care for those who served.",
        "funding for veteran suicide prevention must be a top priority.",
    ],
    va_review: [
        "improving the timeliness of VA disability claims processing remains critical.",
        "enhancing mental healthcare access for veterans must be a top priority.",
        "ensuring seamless coordination between the VA and DoD.",
        "modernizing VA facilities and infrastructure.",
        "reducing wait times for VA appointments is crucial.",
        "improving the VA's electronic health record system implementation.",
    ],
    pact_act_fund: [
        "fully funding and implementing the PACT Act is essential for veterans exposed to toxins.",
        "ensuring the VA has resources to process PACT Act claims efficiently.",
        "outreach efforts to inform veterans about PACT Act benefits require support.",
        "investing in research on toxic exposure health effects.",
        "veterans suffering from toxic exposures deserve timely access to benefits.",
        "the PACT Act represents a commitment we must honor.",
    ],
    pact_act_review: [
        "monitoring the VA's progress in implementing the PACT Act.",
        "continued research into the long-term health effects of toxic exposures.",
        "ensuring healthcare providers are knowledgeable about exposure issues.",
        "streamlining the process for veterans to access PACT Act benefits.",
        "evaluating treatments for conditions linked to toxic exposure.",
        "ensuring outreach reaches all potentially eligible veterans.",
    ],
    // --- Unemployment and Labor ---
    tanf_cut: [
        "TANF's effectiveness needs evaluation; funding should prioritize proven programs.",
        "ensuring TANF work requirements are meaningful.",
        "reducing state flexibility to use TANF funds for unrelated purposes.",
        "evaluating whether TANF benefit levels create work disincentives.",
        "TANF has not kept pace with inflation; its structure may need rethinking.",
        "strengthening accountability for how states use TANF block grants.",
    ],
    tanf_fund: [
        "strengthening the safety net requires adequate TANF funding.",
        "investing in TANF-funded job training helps parents secure employment.",
        "adjusting TANF benefit levels for inflation provides meaningful assistance.",
        "supporting TANF programs that address barriers like childcare.",
        "TANF provides crucial support during crises for families with children.",
        "adequate funding helps TANF promote family well-being.",
    ],
    tanf_review: [
        "evaluating the impact of TANF time limits on family well-being.",
        "improving data collection on TANF outcomes.",
        "ensuring TANF programs are responsive to diverse family needs.",
        "strengthening TANF's role in poverty reduction.",
        "examining the variation in TANF programs across states.",
        "improving access to TANF benefits for eligible families.",
    ],
    child_tax_credit_cut: [
        "the Child Tax Credit structure should be reviewed for fiscal sustainability.",
        "exploring modifications to the CTC, like strengthening work requirements.",
        "balancing the CTC's poverty reduction impact against its cost.",
        "considering whether CTC expansion contributes to inflation.",
        "the CTC's cost is substantial; ensuring it's well-targeted is crucial.",
        "phasing out the credit for higher-income families could save resources.",
    ],
    child_tax_credit_fund: [
        "expanding the Child Tax Credit effectively reduces child poverty.",
        "making recent CTC expansions permanent provides stability for families.",
        "the CTC helps families cover rising costs for essentials.",
        "simplifying CTC claiming processes ensures families receive the benefit.",
        "the CTC is a pro-family policy supporting children's development.",
        "investing in children through the CTC yields long-term benefits.",
    ],
    child_tax_credit_review: [
        "simplifying the process for families to claim the CTC.",
        "evaluating the CTC's impact on parental employment.",
        "ensuring the CTC interacts effectively with other safety net programs.",
        "assessing administrative costs versus benefits delivered by the CTC.",
        "studying the long-term effects of the expanded CTC.",
        "making the full credit available to families with the lowest incomes.",
    ],
    refugee_assistance_cut: [
        "refugee resettlement costs should be managed efficiently.",
        "ensuring adequate security screening alongside resettlement.",
        "balancing humanitarian commitments with fiscal capacity.",
        "exploring ways to increase private sponsorship for refugees.",
        "the focus should be on helping refugees integrate quickly.",
        "limiting resettlement numbers based on available resources.",
    ],
    refugee_assistance_fund: [
        "providing adequate resources for refugee resettlement reflects American values.",
        "investing in effective integration programs helps refugees become self-sufficient.",
        "supporting refugee assistance demonstrates U.S. leadership.",
        "ensuring resettlement agencies have resources to meet initial needs.",
        "refugees contribute culturally and economically over time.",
        "funding for language training and job placement is crucial.",
    ],
    refugee_assistance_review: [
        "improving coordination between agencies and local communities.",
        "evaluating the long-term outcomes of refugees.",
        "ensuring programs are adequately resourced for fluctuating arrivals.",
        "streamlining the process for refugees to obtain work authorization.",
        "addressing housing challenges faced by new arrivals.",
        "supporting mental health services for refugees.",
    ],
    liheap_cut: [
        "LIHEAP funding should target the most vulnerable households.",
        "encouraging energy efficiency provides more sustainable solutions.",
        "ensuring LIHEAP funds supplement individual responsibility.",
        "reviewing LIHEAP administrative costs for savings.",
        "LIHEAP is temporary; long-term solutions are needed.",
        "preventing fraud in LIHEAP applications is important.",
    ],
    liheap_fund: [
        "LIHEAP is crucial for preventing dangerous energy shutoffs.",
        "adequate LIHEAP funding provides a vital safety net against energy poverty.",
        "supporting LIHEAP weatherization helps reduce energy costs permanently.",
        "increased LIHEAP funding is needed to meet growing demand.",
        "LIHEAP helps stabilize housing for low-income families.",
        "preventing energy crises improves public health.",
    ],
    liheap_review: [
        "streamlining the LIHEAP application process improves access.",
        "ensuring equitable distribution of LIHEAP funds based on need.",
        "coordinating LIHEAP with other utility assistance programs.",
        "evaluating LIHEAP's effectiveness in preventing energy crises.",
        "increasing funding for LIHEAP weatherization component.",
        "using data to better target LIHEAP assistance.",
    ],
    nlrb_cut: [
        "the NLRB's actions sometimes face criticism; its funding warrants review.",
        "ensuring the NLRB applies labor laws impartially.",
        "evaluating whether the NLRB's structure suits the modern economy.",
        "questioning certain NLRB enforcement actions.",
        "reducing the NLRB's budget could curb perceived overreach.",
        "streamlining NLRB processes could reduce employer burdens.",
    ],
    nlrb_fund: [
        "protecting workers' rights requires a fully funded NLRB.",
        "adequate resources allow the NLRB to investigate unfair labor practices promptly.",
        "a strong NLRB is essential for maintaining balance between employers and employees.",
        "funding the NLRB ensures fair labor practices are upheld.",
        "the NLRB plays a crucial role in enforcing foundational labor rights.",
        "increased funding is needed to handle rising caseloads.",
    ],
    nlrb_review: [
        "improving the speed and efficiency of NLRB case processing.",
        "ensuring NLRB decisions are consistent and well-reasoned.",
        "adapting NLRB rules to address modern workforce challenges.",
        "maintaining the NLRB's independence and impartiality.",
        "increasing penalties for employers who violate labor laws.",
        "streamlining union election processes.",
    ],
    // --- Education ---
    dept_education_cut: [
        "the federal role in education should be limited, respecting local control.",
        "consolidating duplicative programs within the Department could yield savings.",
        "evaluating the effectiveness of federal education mandates is necessary.",
        "reducing administrative burden associated with federal grants.",
        "returning more education decision-making power to states.",
        "questioning the need for a large federal education bureaucracy.",
    ],
    dept_education_fund: [
        "investing in education is crucial for opportunity and economic growth.",
        "the Department plays a vital role in promoting equity in schools.",
        "adequate federal funding supports key education initiatives.",
        "supporting research and innovation in education through federal grants.",
        "federal leadership is important for addressing national challenges.",
        "funding is needed to support teacher recruitment efforts.",
    ],
    dept_education_review: [
        "simplifying federal grant applications for schools.",
        "improving data collection on the outcomes of federal programs.",
        "ensuring effective enforcement of civil rights laws in education.",
        "strengthening oversight of federal student aid programs.",
        "reducing regulatory burdens on schools while maintaining accountability.",
        "promoting evidence-based practices in education policy.",
    ],
    college_aid_cut: [
        "federal college aid needs reform to address soaring tuition costs.",
        "exploring ways to simplify federal student aid and target it better.",
        "holding colleges more accountable for student outcomes.",
        "questioning the effectiveness of current student loan programs.",
        "reducing federal loan availability could pressure colleges.",
        "shifting towards grants instead of loans for low-income students.",
    ],
    college_aid_fund: [
        "expanding access to affordable higher education requires increased funding.",
        "reducing the burden of student loan debt supports economic security.",
        "simplifying the FAFSA application makes aid more accessible.",
        "investing in programs that support college completion.",
        "higher education remains a key driver of opportunity.",
        "increasing the maximum Pell Grant award is crucial.",
    ],
    college_aid_review: [
        "reviewing student loan interest rates and repayment options.",
        "evaluating the effectiveness of different types of college aid.",
        "ensuring federal aid programs support quality institutions.",
        "strengthening oversight of for-profit colleges.",
        "improving transparency regarding college costs and outcomes.",
        "exploring options for targeted student loan relief.",
    ],
    k12_schools_cut: [
        "federal K-12 funding should primarily supplement state efforts.",
        "reducing federal mandates and returning control to states.",
        "consolidating overlapping federal K-12 grant programs.",
        "evaluating the actual impact of federal K-12 spending.",
        "most K-12 funding comes from state sources; the federal role should be limited.",
        "eliminating ineffective federal education programs.",
    ],
    k12_schools_fund: [
        "targeted federal funding for K-12 is crucial for supporting under-resourced districts.",
        "investing in programs supporting teachers and infrastructure improves quality.",
        "federal support plays a key role in promoting educational equity.",
        "funding programs that address learning loss and student mental health.",
        "investing in early childhood education yields long-term benefits.",
        "supporting students with disabilities requires adequate IDEA funding.",
    ],
    k12_schools_review: [
        "ensuring federal K-12 funds effectively improve outcomes.",
        "evaluating the impact of federal education laws on local districts.",
        "promoting innovation and evidence-based practices.",
        "strengthening support for students with disabilities.",
        "addressing teacher shortages requires comprehensive strategies.",
        "improving data collection to track progress towards equity.",
    ],
    cpb_cut: [
        "in today's media landscape, federal funding for CPB faces scrutiny.",
        "questions about political bias lead to calls for reducing subsidies.",
        "phasing out federal support could encourage reliance on private donations.",
        "evaluating the necessity of CPB funding compared to other needs.",
        "public broadcasting has many alternative funding sources.",
        "taxpayer dollars should perhaps not be used to fund media outlets.",
    ],
    cpb_fund: [
        "CPB provides essential funding for quality educational programming.",
        "public broadcasting serves underserved communities.",
        "federal support ensures the independence of public radio and television.",
        "CPB funding supports local stations providing community services.",
        "public media plays a crucial role in civic education.",
        "CPB supports non-commercial programming for children.",
    ],
    cpb_review: [
        "ensuring CPB funding distribution is fair and transparent.",
        "evaluating mechanisms for maintaining editorial independence.",
        "assessing public broadcasting's role in the digital age.",
        "strengthening oversight of how CPB funds are used.",
        "promoting transparency in CPB operations.",
        "ensuring public media reflects the diversity of the public.",
    ],
    imls_cut: [
        "federal IMLS funding could potentially be reduced.",
        "prioritizing IMLS grants towards programs with the broadest impact.",
        "evaluating the specific outcomes achieved through IMLS funding.",
        "considering whether IMLS functions could be absorbed elsewhere.",
        "libraries and museums primarily rely on local funding; the federal role can be smaller.",
        "focusing IMLS resources on specific national initiatives.",
    ],
    imls_fund: [
        "IMLS provides crucial federal support for libraries and museums.",
        "IMLS funding helps libraries bridge the digital divide.",
        "federal support through IMLS leverages state funding.",
        "IMLS grants support innovation in library and museum services.",
        "libraries and museums are essential community anchors.",
        "IMLS funding promotes access to information.",
    ],
    imls_review: [
        "ensuring IMLS grants are accessible to institutions of all sizes.",
        "focusing IMLS initiatives on priorities like digital literacy.",
        "improving data collection on the impact of IMLS programs.",
        "strengthening IMLS's role in promoting lifelong learning.",
        "supporting efforts to digitize collections.",
        "enhancing collaboration between libraries and museums.",
    ],
    // --- Food and Agriculture ---
    snap_cut: [
        "reforming SNAP to strengthen work requirements could lead to savings.",
        "ensuring SNAP benefits are used for nutritious food warrants consideration.",
        "tightening SNAP eligibility requires balancing fiscal concerns.",
        "reducing SNAP fraud through better verification methods.",
        "promoting self-sufficiency should be the primary goal of SNAP.",
        "evaluating the impact of SNAP benefit levels on work incentives.",
    ],
    snap_fund: [
        "SNAP is the nation's most effective anti-hunger program.",
        "strengthening SNAP benefits reduces food insecurity and improves health.",
        "maintaining broad SNAP eligibility is crucial during downturns.",
        "SNAP benefits provide significant economic stimulus.",
        "hunger is a solvable problem; SNAP is a key solution.",
        "adequate SNAP benefits help families afford a basic diet.",
    ],
    snap_review: [
        "simplifying the SNAP application process improves access.",
        "improving SNAP Employment & Training programs.",
        "ensuring SNAP benefits reflect the actual cost of food.",
        "using technology to make SNAP benefits easier to use.",
        "evaluating the effectiveness of restrictions on SNAP purchases.",
        "coordinating SNAP with other nutrition programs.",
    ],
    school_lunch_cut: [
        "reviewing nutritional standards and costs of the School Lunch Program.",
        "ensuring school meal programs target assistance effectively.",
        "exploring alternative models for providing school meals.",
        "balancing meal quality with program cost.",
        "reducing waste in school meal programs is important.",
        "simplifying regulations for participating schools.",
    ],
    school_lunch_fund: [
        "expanding access to free school meals ensures children have nutrition to learn.",
        "investing in universal free school meals reduces stigma.",
        "supporting programs using fresh, local foods enhances quality.",
        "adequate funding allows schools to meet nutritional standards.",
        "school meals are critical for food-insecure households.",
        "funding is needed to upgrade school kitchen equipment.",
    ],
    school_lunch_review: [
        "improving the nutritional quality and appeal of school meals.",
        "streamlining the application process for free meals.",
        "ensuring adequate funding for schools to meet standards.",
        "reducing food waste within school meal programs.",
        "evaluating the impact of school meals on student health.",
        "increasing support for farm-to-school programs.",
    ],
    fsa_cut: [
        "reforming farm subsidies administered by FSA is needed.",
        "limiting FSA payments to large agricultural corporations.",
        "phasing out certain commodity support programs could save money.",
        "shifting FSA resources from subsidies towards conservation.",
        "farm subsidies often benefit large agribusinesses.",
        "ending duplicative or outdated FSA programs.",
    ],
    fsa_fund: [
        "the FSA provides crucial support for farmers.",
        "adequate funding for FSA loan programs helps beginning farmers.",
        "investing in FSA conservation programs protects soil and water.",
        "FSA programs help ensure a stable food supply.",
        "disaster assistance through FSA is vital for farmers.",
        "supporting FSA efforts to promote climate-smart agriculture.",
    ],
    fsa_review: [
        "improving accessibility of FSA programs for small farmers.",
        "ensuring FSA disaster assistance is timely.",
        "evaluating the effectiveness of commodity support.",
        "modernizing FSA technology and service delivery.",
        "increasing transparency in farm subsidy payments.",
        "strengthening FSA's role in supporting local food systems.",
    ],
    wic_cut: [
        "reviewing WIC's administrative costs for efficiency.",
        "targeting WIC benefits effectively to those most at risk.",
        "coordinating WIC services with other health programs.",
        "ensuring WIC food packages offer the best nutritional value.",
        "evaluating the long-term impact of WIC participation.",
        "streamlining WIC certification processes.",
    ],
    wic_fund: [
        "WIC provides critical nutritional support, improving health outcomes.",
        "fully funding WIC ensures all eligible participants receive benefits.",
        "investing in WIC is cost-effective for long-term health.",
        "WIC's nutrition education components are valuable.",
        "WIC supports healthy pregnancies and gives children a stronger start.",
        "increasing the value of WIC benefits for fruits and vegetables.",
    ],
    wic_review: [
        "modernizing WIC food packages to align with dietary guidelines.",
        "improving the WIC shopping experience through EBT systems.",
        "strengthening WIC's role in providing nutrition education.",
        "increasing WIC participation rates through better outreach.",
        "evaluating the effectiveness of WIC's breastfeeding support.",
        "using technology to improve WIC service delivery.",
    ],
    // --- Government Operations ---
    fdic_review: [
        "ensuring the FDIC effectively manages the deposit insurance fund.",
        "maintaining public confidence requires demonstrating FDIC independence.",
        "evaluating the adequacy of FDIC resources to handle potential bank failures.",
        "assessing the FDIC's role in addressing emerging financial risks.",
        "improving FDIC resolution planning for large institutions.",
        "reviewing deposit insurance coverage levels.",
    ],
    irs_cut: [
        "IRS funding should prioritize efficient tax administration.",
        "concerns about IRS overreach lead to calls for budget constraints.",
        "simplifying the tax code itself could be more effective.",
        "ensuring IRS resources are used fairly.",
        "reducing the complexity of tax filing lessens IRS intervention.",
        "increasing oversight to prevent misuse of IRS authority.",
    ],
    irs_fund: [
        "adequate IRS funding is essential to close the 'tax gap'.",
        "investing in IRS modernization improves efficiency and service.",
        "effective IRS enforcement targeting tax evasion yields revenue.",
        "providing IRS resources to combat sophisticated tax evasion.",
        "a well-funded IRS ensures everyone pays their fair share.",
        "improving IRS customer service requires sufficient staffing.",
    ],
    irs_review: [
        "ensuring the IRS uses resources fairly requires oversight.",
        "improving IRS taxpayer service, including phone support.",
        "protecting taxpayer rights and ensuring due process.",
        "focusing IRS enforcement on areas with high non-compliance.",
        "continuing efforts to simplify tax filing.",
        "enhancing IRS cybersecurity to protect taxpayer data.",
    ],
    federal_courts_cut: [
        "reviewing federal court operations for efficiencies.",
        "exploring alternatives to litigation might reduce caseloads.",
        "careful budgeting is necessary, but must not compromise function.",
        "evaluating the necessity of new courthouse construction.",
        "streamlining court procedures could save resources.",
    ],
    federal_courts_fund: [
        "a well-functioning judiciary requires sufficient funding.",
        "investing in the federal courts ensures timely access to justice.",
        "adequate resources are needed to protect judges.",
        "funding technology upgrades enhances court efficiency.",
        "addressing judicial vacancies requires funding.",
        "supporting specialized courts is important.",
    ],
    federal_courts_review: [
        "addressing judicial vacancies promptly to reduce backlogs.",
        "improving access to courts for low-income individuals.",
        "modernizing court technology, including electronic filing.",
        "ensuring the judiciary remains independent.",
        "evaluating different case management strategies.",
        "promoting diversity within the federal judiciary.",
    ],
    public_defenders_fund: [
        "ensuring the right to counsel requires adequate funding.",
        "underfunded public defense systems compromise representation.",
        "investing in public defense ensures fairness in the justice system.",
        "addressing excessive caseloads requires increased resources.",
        "providing parity in resources between prosecutors and defenders.",
        "supporting training for public defenders.",
    ],
    public_defenders_review: [
        "addressing high caseloads and ensuring adequate resources.",
        "promoting pay parity between public defenders and prosecutors.",
        "evaluating models for providing indigent defense.",
        "supporting professional development for public defenders.",
        "ensuring defenders have access to expert witnesses.",
        "collecting data on public defense workloads.",
    ],
    usps_review: [
        "reviewing congressional mandates impacting USPS finances.",
        "supporting USPS modernization efforts.",
        "allowing USPS flexibility to adjust service and pricing.",
        "ensuring USPS can fulfill its universal service obligation.",
        "evaluating the financial performance of the USPS.",
        "considering potential new revenue streams for the USPS.",
    ],
    cfpb_cut: [
        "the CFPB's authority and funding structure warrant scrutiny.",
        "concerns about CFPB regulations being overly burdensome.",
        "ensuring the CFPB focuses on clear consumer harm.",
        "limiting the CFPB's power or budget is sometimes proposed.",
        "evaluating the economic impact of CFPB rules.",
        "increasing congressional oversight of the CFPB.",
    ],
    cfpb_fund: [
        "the CFPB plays a vital role in protecting consumers.",
        "strong CFPB enforcement returns billions to harmed consumers.",
        "funding CFPB consumer education initiatives empowers individuals.",
        "adequate resources allow CFPB to supervise large institutions.",
        "the CFPB provides a crucial voice for consumers.",
        "supporting CFPB efforts to promote fair lending.",
    ],
    cfpb_review: [
        "ensuring the CFPB's rulemaking process is transparent.",
        "improving coordination between CFPB and other regulators.",
        "evaluating the effectiveness of CFPB enforcement actions.",
        "maintaining the CFPB's independence.",
        "enhancing the CFPB's complaint database.",
        "adapting CFPB oversight to address emerging fintech.",
    ],
    mbda_cut: [
        "evaluating MBDA's effectiveness compared to broader SBA programs.",
        "ensuring MBDA programs deliver measurable results.",
        "consolidating business development programs could increase efficiency.",
        "questioning the need for a separate agency focused on minority businesses.",
    ],
    mbda_fund: [
        "the MBDA plays a unique role in addressing systemic barriers.",
        "investing in MBDA programs helps create jobs in underserved communities.",
        "expanding MBDA's reach can help close the racial wealth gap.",
        "supporting MBDA strengthens the overall economy.",
        "MBDA provides tailored assistance for minority entrepreneurs.",
    ],
    mbda_review: [
        "improving access to capital for minority-owned businesses via MBDA.",
        "strengthening partnerships between MBDA and other agencies.",
        "enhancing data collection on minority-owned businesses.",
        "ensuring MBDA programs are effectively targeted.",
        "increasing MBDA's capacity to support businesses in high-growth sectors.",
    ],
    usich_review: [
        "evaluating USICH's effectiveness in coordinating homelessness response.",
        "ensuring USICH's plan aligns with evidence-based practices like Housing First.",
        "strengthening USICH's ability to promote collaboration.",
        "improving data collection on federal homelessness initiatives.",
        "clarifying USICH's role relative to HUD.",
    ],
    // --- Housing and Community ---
    fema_cut: [
        "FEMA's disaster response requires review for efficiency.",
        "ensuring FEMA funds prioritize immediate life-saving needs.",
        "balancing federal aid with stronger state preparedness.",
        "scrutinizing FEMA contracting practices.",
        "reducing bureaucratic delays in FEMA assistance.",
        "evaluating the cost-benefit of certain mitigation projects.",
    ],
    fema_fund: [
        "increasing disaster frequency requires robust FEMA funding.",
        "investing in FEMA's capacity provides timely assistance.",
        "supporting FEMA's pre-disaster mitigation reduces long-term costs.",
        "ensuring FEMA has resources to handle large-scale disasters.",
        "adequate funding for FEMA is crucial for national resilience.",
        "supporting FEMA's floodplain management programs.",
    ],
    fema_review: [
        "improving the speed and equity of FEMA's individual assistance.",
        "strengthening FEMA's coordination with state governments.",
        "ensuring FEMA programs promote climate resilience.",
        "increasing transparency in FEMA spending.",
        "modernizing FEMA's technology infrastructure.",
        "evaluating the effectiveness of public assistance grants.",
    ],
    fema_drf_fund: [
        "maintaining a sufficiently funded Disaster Relief Fund is crucial.",
        "predictable DRF funding provides stability for planning.",
        "replenishing the DRF proactively ensures resources are available.",
        "ensuring the DRF can cover rising disaster costs.",
        "a healthy DRF balance allows FEMA to respond quickly.",
    ],
    fema_drf_review: [
        "improving transparency regarding DRF spending.",
        "ensuring DRF funding formulas are equitable.",
        "evaluating the long-term solvency of the DRF.",
        "streamlining processes for accessing DRF funds.",
        "congressional oversight of DRF management.",
    ],
    hud_cut: [
        "HUD programs need review for effectiveness.",
        "streamlining HUD bureaucracy and reducing regulations.",
        "evaluating the cost-effectiveness of different HUD programs.",
        "encouraging more private sector innovation in housing.",
        "reducing funding for programs with limited impact.",
        "consolidating overlapping HUD programs.",
    ],
    hud_fund: [
        "tackling the affordable housing crisis requires investment in HUD programs.",
        "expanding HUD resources is essential for reducing homelessness.",
        "investing in affordable housing development stimulates economies.",
        "funding HUD programs that support community development.",
        "millions are waitlisted for housing assistance due to inadequate funding.",
        "supporting HUD's efforts to preserve affordable housing.",
    ],
    hud_review: [
        "improving the efficiency of HUD's rental assistance programs.",
        "addressing the capital repair backlog in public housing.",
        "ensuring HUD programs effectively promote fair housing.",
        "strengthening HUD oversight of grantees.",
        "simplifying HUD grant application processes.",
        "evaluating the long-term impact of HUD programs.",
    ],
    head_start_cut: [
        "Head Start programs should be evaluated for long-term impact.",
        "improving quality standards across Head Start centers.",
        "ensuring Head Start funding complements state pre-K programs.",
        "focusing Head Start resources on the most effective interventions.",
        "questioning the cost-effectiveness of Head Start.",
    ],
    head_start_fund: [
        "Head Start provides critical comprehensive early childhood services.",
        "expanding access to high-quality Head Start closes achievement gaps.",
        "adequate funding allows Head Start to maintain quality standards.",
        "Head Start demonstrably improves long-term outcomes.",
        "investing in early childhood through Head Start yields high returns.",
    ],
    head_start_review: [
        "strengthening Head Start performance standards.",
        "improving coordination between Head Start and K-12 systems.",
        "enhancing support for Head Start staff.",
        "focusing Head Start on evidence-based practices.",
        "evaluating the effectiveness of health components.",
        "increasing access to full-day Head Start programs.",
    ],
    public_housing_cut: [
        "the traditional public housing model faces challenges; exploring alternatives.",
        "improving management efficiency in public housing.",
        "shifting towards housing vouchers is sometimes proposed.",
        "addressing the root causes of issues within public housing.",
        "reducing the deferred maintenance backlog requires new strategies.",
    ],
    public_housing_fund: [
        "addressing the capital repair backlog in public housing is crucial.",
        "investing in the preservation of public housing.",
        "funding is needed to support resident services and improve security.",
        "public housing provides essential homes for low-income families.",
        "supporting programs like RAD to leverage private funding.",
    ],
    public_housing_review: [
        "implementing strategies to address crime in public housing.",
        "promoting resident involvement and opportunities.",
        "exploring mixed-finance models to revitalize communities.",
        "ensuring public housing is well-maintained.",
        "addressing lead paint and other environmental hazards.",
        "improving HUD oversight of local Public Housing Authorities.",
    ],
    // --- Energy and Environment ---
    epa_cut: [
        "EPA regulations should balance environmental goals with economic impacts.",
        "streamlining EPA permitting processes is needed.",
        "evaluating the cost-effectiveness of specific EPA regulations.",
        "ensuring the EPA relies on sound, transparent science.",
        "reducing EPA's budget could curb perceived overreach.",
        "returning more environmental authority to states.",
    ],
    epa_fund: [
        "addressing critical environmental challenges requires a well-funded EPA.",
        "investing in EPA enforcement ensures laws are upheld.",
        "supporting EPA's scientific research provides basis for policy.",
        "funding EPA programs that protect air and water quality.",
        "EPA plays a crucial role in addressing environmental justice.",
        "funding is needed to clean up Superfund sites.",
    ],
    epa_review: [
        "improving the timeliness of EPA's permitting processes.",
        "ensuring EPA regulations reflect the best available science.",
        "strengthening EPA's capacity to address environmental justice.",
        "enhancing EPA transparency and public participation.",
        "modernizing EPA's enforcement tools.",
        "improving coordination between EPA and state agencies.",
    ],
    forest_service_cut: [
        "reviewing Forest Service operations for efficiencies.",
        "balancing environmental protection with economic uses.",
        "prioritizing Forest Service resources towards wildfire prevention.",
        "ensuring cost-effectiveness in Forest Service land management.",
        "evaluating the need for certain Forest Service programs.",
        "reducing bureaucratic hurdles for forest management.",
    ],
    forest_service_fund: [
        "increased Forest Service funding is needed to address the wildfire crisis.",
        "investing in the health of national forests protects watersheds.",
        "adequate resources allow sustainable management of national forests.",
        "supporting federal wildland firefighters is critical.",
        "funding is needed to address deferred maintenance.",
    ],
    forest_service_review: [
        "improving the effectiveness of hazardous fuels treatments.",
        "strengthening partnerships for wildfire response.",
        "ensuring adequate compensation for wildland firefighters.",
        "using the best science to guide forest restoration.",
        "improving planning processes for forest management.",
        "balancing recreational access with resource protection.",
    ],
    noaa_cut: [
        "evaluating NOAA programs for potential duplication.",
        "prioritizing NOAA resources towards core functions.",
        "ensuring efficiency in NOAA's satellite programs.",
        "considering if private sector could provide some services.",
        "streamlining NOAA's administrative structure.",
    ],
    noaa_fund: [
        "NOAA provides essential services like weather forecasts.",
        "investing in NOAA's prediction capabilities protects lives.",
        "supporting NOAA's research on oceans and climate.",
        "funding NOAA helps ensure sustainable marine resources.",
        "NOAA's data underpin numerous economic sectors.",
    ],
    noaa_review: [
        "improving the accuracy of NOAA weather forecasts.",
        "enhancing NOAA's role in supporting coastal resilience.",
        "ensuring sustainable fisheries management.",
        "modernizing NOAA's observation systems.",
        "strengthening NOAA's climate modeling capabilities.",
        "improving coordination within NOAA.",
    ],
    renewable_energy_cut: [
        "government subsidies for mature renewables should be phased out.",
        "focusing federal energy R&D on breakthrough technologies.",
        "evaluating the cost-effectiveness of DOE renewable programs.",
        "allowing market forces to drive renewable deployment.",
        "reducing subsidies could lower energy costs short-term.",
        "questioning the fairness of industry-specific subsidies.",
    ],
    renewable_energy_fund: [
        "accelerating the clean energy transition requires federal investment.",
        "supporting renewable energy creates jobs and enhances security.",
        "investing in grid modernization is crucial for renewables.",
        "funding research into next-generation clean energy.",
        "tax credits level the playing field against fossil fuels.",
    ],
    renewable_energy_review: [
        "ensuring federal programs drive innovation.",
        "improving permitting for renewable projects.",
        "targeting investments towards advanced technologies.",
        "analyzing grid impacts of increasing renewables.",
        "supporting workforce development for clean energy.",
        "evaluating the effectiveness of different incentives.",
    ],
    nps_cut: [
        "reviewing National Park Service operations for efficiencies.",
        "exploring increased reliance on visitor fees.",
        "prioritizing NPS resources towards deferred maintenance.",
        "balancing visitor access with resource protection.",
        "evaluating the need for expanding the park system.",
        "streamlining NPS management structures.",
    ],
    nps_fund: [
        "protecting America's heritage requires adequate NPS funding.",
        "addressing deferred maintenance in National Parks is crucial.",
        "investing in National Parks preserves resources.",
        "providing sufficient resources for NPS staff.",
        "funding is needed to adapt parks to climate change.",
        "expanding educational programs in parks.",
    ],
    nps_review: [
        "developing sustainable solutions for NPS maintenance backlog.",
        "managing increasing visitor numbers sustainably.",
        "enhancing interpretation and visitor experiences.",
        "improving infrastructure within National Parks.",
        "strengthening NPS partnerships with communities.",
        "ensuring NPS uses best science for resource management.",
    ],
    // --- International Affairs ---
    diplomacy_cut: [
        "reviewing State Department operations for efficiencies.",
        "evaluating the necessity of all diplomatic programs.",
        "balancing investments in diplomacy with defense spending.",
        "ensuring diplomatic resources align with core objectives.",
        "questioning spending on cultural exchange programs.",
        "reducing contributions to certain international organizations.",
    ],
    diplomacy_fund: [
        "robust funding for diplomacy strengthens U.S. influence.",
        "investing in our diplomatic corps is essential.",
        "supporting public diplomacy enhances mutual understanding.",
        "effective diplomacy can avoid costlier interventions.",
        "funding is needed to maintain secure embassies.",
        "supporting multilateral diplomacy.",
    ],
    diplomacy_review: [
        "ensuring State Department has resources for global challenges.",
        "modernizing diplomatic tools and communication.",
        "strengthening coordination between foreign affairs agencies.",
        "supporting the professional development of diplomats.",
        "evaluating the effectiveness of diplomatic initiatives.",
        "ensuring U.S. diplomacy promotes human rights.",
    ],
    usaid_cut: [
        "USAID programs require rigorous oversight for effectiveness.",
        "focusing foreign aid where it achieves measurable outcomes.",
        "reducing administrative overhead within USAID.",
        "ensuring foreign aid does not create dependency.",
        "prioritizing aid based on strategic importance.",
        "shifting towards loan guarantees instead of direct grants.",
    ],
    usaid_fund: [
        "U.S. foreign aid addresses global poverty and improves health.",
        "investing in global development prevents conflicts.",
        "adequate USAID funding allows response to humanitarian crises.",
        "supporting USAID advances American values and interests.",
        "funding global health programs saves lives.",
        "supporting education and economic opportunity abroad.",
    ],
    usaid_review: [
        "improving measurement and evaluation of USAID programs.",
        "strengthening local partnerships for sustainable development.",
        "ensuring USAID programs have strong safeguards against corruption.",
        "adapting USAID strategies to address climate change.",
        "improving coordination between USAID and other donors.",
        "ensuring USAID programs are responsive to recipient needs.",
    ],
    usaid_climate_cut: [
        "international climate aid needs careful evaluation.",
        "prioritizing climate finance towards high-impact projects.",
        "ensuring transparency in how U.S. climate aid is used.",
        "balancing international climate aid against domestic needs.",
        "questioning contributions to large international climate funds.",
    ],
    usaid_climate_fund: [
        "addressing the global climate crisis requires U.S. leadership.",
        "international climate finance helps mitigate emissions.",
        "investing in climate adaptation abroad can reduce instability.",
        "supporting clean energy transitions benefits global climate goals.",
        "meeting U.S. commitments under climate agreements.",
    ],
    usaid_climate_review: [
        "ensuring U.S. climate aid aligns with development goals.",
        "improving coordination of climate finance across agencies.",
        "developing robust monitoring systems for climate projects.",
        "leveraging private sector investment for climate solutions.",
        "focusing climate aid on the most vulnerable countries.",
        "ensuring climate finance supports locally led efforts.",
    ],
    // --- Law Enforcement ---
    deportations_border_cut: [
        "focusing border resources on humane processing may be more effective.",
        "reviewing the cost and effectiveness of immigrant detention.",
        "prioritizing interior enforcement based on public safety risks.",
        "investing in technology at ports of entry could be effective.",
        "reducing funding for ICE detention centers.",
    ],
    deportations_border_fund: [
        "securing borders requires resources for personnel and technology.",
        "funding for ICE is needed for interior enforcement.",
        "investing in border security is essential for sovereignty.",
        "providing resources to combat drug smuggling.",
        "supporting efforts to expedite asylum processing.",
    ],
    deportations_border_review: [
        "ensuring humane treatment in immigration enforcement.",
        "improving efficiency in immigration courts.",
        "enhancing coordination between CBP, ICE, and HHS.",
        "utilizing technology effectively for border management.",
        "evaluating different border security strategies.",
        "addressing the root causes of migration.",
    ],
    federal_prisons_cut: [
        "exploring criminal justice reforms to lower incarceration rates.",
        "expanding the use of alternatives to imprisonment.",
        "improving rehabilitation programs to reduce recidivism.",
        "addressing prison overcrowding through sentencing reform.",
        "evaluating the cost-effectiveness of private prisons.",
        "reducing sentences for certain low-level drug offenses.",
    ],
    federal_prisons_fund: [
        "maintaining safe federal prisons requires adequate funding.",
        "investing in evidence-based education programs reduces recidivism.",
        "addressing chronic understaffing among correctional officers.",
        "providing adequate mental health care for inmates.",
        "funding is needed to upgrade aging prison infrastructure.",
    ],
    federal_prisons_review: [
        "implementing practices to reduce violence within prisons.",
        "enhancing oversight of healthcare services for inmates.",
        "improving reentry programs to support transitions.",
        "evaluating different correctional programs.",
        "addressing staffing shortages and improving officer training.",
        "expanding use of the First Step Act's earned time credits.",
    ],
    // --- Transportation ---
    highways_cut: [
        "federal highway funding should prioritize maintenance over expansion.",
        "ensuring states use federal highway funds efficiently.",
        "balancing highway investments with support for transit.",
        "exploring user fees to reduce reliance on general funds.",
        "re-evaluating the federal gas tax.",
        "reducing earmarks and focusing funding on national significance.",
    ],
    highways_fund: [
        "modernizing aging highway infrastructure requires investment.",
        "predictable federal funding allows states to plan projects.",
        "investing in highway improvements enhances safety and the economy.",
        "upgrading structurally deficient bridges is critical.",
        "funding projects that incorporate modern safety features.",
    ],
    highways_review: [
        "prioritizing federal funding towards high-impact projects.",
        "streamlining environmental review for infrastructure projects.",
        "incorporating technology to improve traffic flow.",
        "ensuring highway projects are resilient to climate change.",
        "improving coordination between transportation planning levels.",
        "evaluating the equity impacts of highway investments.",
    ],
    public_transit_cut: [
        "federal transit funding should prioritize high-ridership systems.",
        "encouraging local governments to bear larger share of costs.",
        "evaluating the cost-effectiveness of transit expansion projects.",
        "ensuring transit agencies operate efficiently.",
        "questioning subsidies for routes with low ridership.",
        "promoting innovation in transit service delivery.",
    ],
    public_transit_fund: [
        "investing in public transit reduces congestion and emissions.",
        "adequate funding helps agencies maintain safe service.",
        "supporting transit provides affordable transportation options.",
        "funding the transition to cleaner transit fleets.",
        "expanding transit service connects more people to jobs.",
    ],
    public_transit_review: [
        "improving transit service frequency and reliability.",
        "integrating transit planning with land use planning.",
        "ensuring transit systems are accessible.",
        "using technology to improve the rider experience.",
        "evaluating different funding models for transit.",
        "strengthening safety and security on transit systems.",
    ],
    tsa_cut: [
        "reviewing TSA screening procedures for efficiency.",
        "evaluating the cost-effectiveness of specific TSA technologies.",
        "ensuring appropriate staffing levels.",
        "comparing TSA performance against international counterparts.",
        "reducing reliance on certain behavioral detection techniques.",
    ],
    tsa_fund: [
        "maintaining aviation security requires adequate TSA funding.",
        "investing in advanced screening technologies enhances security.",
        "providing competitive pay for TSA officers improves retention.",
        "adapting TSA protocols to address emerging threats.",
        "funding trusted traveler programs enhances efficiency.",
    ],
    tsa_review: [
        "balancing rigorous security with passenger facilitation.",
        "continuously adapting security protocols to counter threats.",
        "improving coordination between TSA and intelligence agencies.",
        "evaluating screening methods through rigorous testing.",
        "enhancing TSA officer training on threat detection.",
        "improving the process for resolving screening complaints.",
    ],
    faa_cut: [
        "ensuring the FAA operates efficiently, especially NextGen.",
        "evaluating the necessity of all FAA programs.",
        "streamlining aircraft certification processes.",
        "reducing bureaucratic delays within the FAA.",
        "questioning spending on projects with limited benefits.",
    ],
    faa_fund: [
        "ensuring airspace safety requires robust FAA funding.",
        "adequate FAA resources are critical for system safety.",
        "investing in NextGen enhances efficiency and safety.",
        "funding FAA oversight of manufacturing and operations.",
        "addressing air traffic controller shortage requires funding.",
    ],
    faa_review: [
        "addressing air traffic controller staffing shortages.",
        "accelerating the implementation of NextGen.",
        "enhancing FAA oversight of aircraft manufacturing.",
        "improving coordination with international authorities.",
        "streamlining integration of new technologies like drones.",
        "evaluating runway safety initiatives.",
    ],
    amtrak_cut: [
        "Amtrak's reliance on subsidies warrants scrutiny.",
        "focusing federal rail investments on viable corridors.",
        "exploring increased private sector involvement.",
        "demanding greater financial accountability from Amtrak.",
        "phasing out subsidies for low-ridership routes.",
    ],
    amtrak_fund: [
        "investing in Amtrak offers alternative to congested highways.",
        "adequate funding allows Amtrak to upgrade infrastructure.",
        "supporting passenger rail connects communities.",
        "expanding Amtrak service to underserved areas.",
        "funding improvements on the Northeast Corridor.",
    ],
    amtrak_review: [
        "improving Amtrak's on-time performance and customer service.",
        "developing a clear long-term plan for passenger rail.",
        "ensuring fair access for Amtrak on freight railroad tracks.",
        "evaluating the benefits of specific Amtrak investments.",
        "modernizing Amtrak stations and improving accessibility.",
        "exploring high-speed rail development.",
    ],
    // --- Science ---
    nasa_cut: [
        "NASA's budget requires prioritization, focusing on core science.",
        "evaluating the cost-effectiveness of human vs. robotic exploration.",
        "encouraging cost control in NASA project management.",
        "scrutinizing the costs of large flagship programs.",
        "increasing reliance on commercial partners for routine activities.",
    ],
    nasa_fund: [
        "investing in NASA fuels scientific discovery and innovation.",
        "funding NASA missions expands human knowledge.",
        "supporting NASA maintains U.S. leadership in space.",
        "NASA programs inspire the next generation (STEM).",
        "funding Earth science missions provides critical climate data.",
    ],
    nasa_review: [
        "ensuring NASA maintains a balanced portfolio.",
        "improving management of costs for large missions.",
        "strengthening partnerships with the commercial space industry.",
        "prioritizing NASA missions based on scientific merit.",
        "enhancing international collaboration in space.",
        "supporting NASA's aeronautics research.",
    ],
    nsf_cut: [
        "ensuring NSF grants target fundamental, high-impact research.",
        "evaluating the balance of NSF funding across disciplines.",
        "minimizing administrative overhead associated with NSF grants.",
        "prioritizing NSF funding based on national needs.",
        "questioning funding for social science research with limited application.",
    ],
    nsf_fund: [
        "the NSF provides essential funding for fundamental research.",
        "investing in basic science through NSF is critical for competitiveness.",
        "supporting NSF programs broadens participation in STEM fields.",
        "NSF funding trains the next generation of scientists.",
        "funding major research infrastructure supported by NSF.",
    ],
    nsf_review: [
        "maintaining the integrity of NSF's merit review process.",
        "enhancing NSF's role in translating basic research.",
        "supporting STEM education initiatives.",
        "ensuring NSF investments align with national interests.",
        "improving coordination between NSF and other agencies.",
        "promoting open science and data sharing practices.",
    ],
    nasa_spacex_cut: [
        "NASA's reliance on partners like SpaceX needs strong oversight.",
        "promoting robust competition among commercial space providers.",
        "evaluating the strategy for public-private partnerships.",
        "questioning the level of subsidy provided.",
        "demanding greater transparency on commercial contracts.",
    ],
    nasa_spacex_review: [
        "ensuring rigorous safety standards for commercial missions.",
        "maintaining transparency regarding costs of commercial contracts.",
        "balancing commercial partnerships with NASA's internal capabilities.",
        "defining clear roles between NASA and commercial partners.",
        "fostering a competitive commercial space ecosystem.",
        "planning for the future of Low Earth Orbit operations.",
    ],
    // --- Generic Fallbacks (Least specific) ---
    default_cut: [
        "this program's funding level appears disproportionately high.",
        "resources allocated here might be better utilized elsewhere.",
        "a reduction in funding for this area should be considered.",
        "the justification for this level of spending requires scrutiny.",
        "this area's funding warrants review for potential savings.",
    ],
    default_fund: [
        "adequate investment in this area is likely necessary.",
        "increased resources could potentially unlock greater public benefit.",
        "ensuring this program has sufficient funding seems prudent.",
        "this appears to be a valuable program deserving support.",
        "increased investment here could yield significant benefits.",
    ],
    default_review: [
        "closer examination of this program's spending is warranted.",
        "regular oversight is needed to confirm this program delivers value.",
        "an independent evaluation of this program's effectiveness is needed.",
        "transparency regarding this program's spending should be improved.",
        "this program requires review to optimize performance.",
    ],
};


// Paragraph about BUDGET/DEBT
export const BUDGET_DEBT: Record<Tone, string> = {
    0: "Additionally, while addressing specific programs, I hope Congress will also maintain a focus on long-term fiscal responsibility and work towards a sustainable budget path.",
    1: "Beyond these specific items, I strongly urge you to prioritize measures that lead to greater fiscal sustainability and begin addressing our growing national debt.",
    2: "Furthermore, addressing the national debt cannot be postponed. Fiscal discipline must be central to every spending decision Congress makes, starting now.",
    3: "Critically, the soaring national debt is an existential threat to our economic future. A concrete, aggressive debt-reduction plan is not optional—it is an absolute necessity.",
};

// CALL TO ACTION (More direct and demanding at higher tones)
export const CALL_TO_ACTION: Record<Tone, string> = {
    0: "Could you please share your perspective on how these specific funding issues might be addressed in upcoming budget discussions? I appreciate your time and service.",
    1: "I request that you outline the steps you intend to take to address these spending concerns and promote greater fiscal responsibility. Keeping constituents informed is important.",
    2: "I expect a detailed response outlining the concrete actions you will champion to correct these spending priorities and aggressively tackle the national debt. Accountability is essential.",
    3: "I demand a prompt and specific action plan from your office detailing how you will fight to realign this irresponsible spending and put our nation on a sustainable fiscal path. Failure to act is unacceptable.",
};

// Sentence openers to introduce an item's funding level (More varied)
// These should function well as starting points for sentences or major clauses.
export const ITEM_OPENERS: Record<FundingActionRationale, string[]> = {
    cut: [
        "Regarding funding for {ITEM}, my view is that it",
        "When it comes to {ITEM}, my perspective is that its funding",
        "The allocation for {ITEM}",
        "Funding levels for {ITEM}",
        "Concerning {ITEM}, the budget allocation",
        "Turning to {ITEM}, I believe its funding",
        "The expenditure on {ITEM}",
        "Considering the budget for {ITEM}, it",
        "It seems prudent to examine the funding for {ITEM}, which",
    ],
    fund: [
        "Regarding {ITEM}, I believe increased investment is warranted, as its funding",
        "For {ITEM}, adequate funding is crucial, meaning its budget",
        "It's important to support {ITEM}; therefore, its funding",
        "Considering {ITEM}, the current budget",
        "When discussing {ITEM}, it seems clear that its funding",
        "Investment in {ITEM}",
        "To ensure the success of {ITEM}, its funding",
        "Prioritizing {ITEM} means its funding",
        "The value provided by {ITEM} suggests its funding",
    ],
    review: [
        "The funding for {ITEM} requires careful review, as its budget",
        "With respect to {ITEM}, its budget",
        "Oversight of {ITEM} is critical, meaning its funding",
        "The allocation towards {ITEM}",
        "For {ITEM}, ensuring efficiency means its funding",
        "Evaluating {ITEM} suggests its budget",
        "A closer look at {ITEM} indicates its funding",
        "Scrutinizing the budget for {ITEM} reveals its funding",
        "To optimize {ITEM}, its funding",
    ]
};


// Connectors between action phrase and rationale (varied)
// Classified by whether they typically start a new sentence or connect clauses.
export const RATIONALE_CONNECTORS: { polite: string[], firm: string[] } = {
    polite: [
        // Clause connectors (often follow comma or semicolon)
        "; specifically,", "; for instance,", "; for example,", "; namely,", "; particularly,",
        // Sentence starters (often follow period)
        ". My reasoning is that", ". I believe this because", ". This is important as", ". Specifically,", ". For instance,"
    ],
    firm: [
        // Clause connectors
        "; specifically,", "; simply put,", "; to be precise,", "; in fact,",
        // Sentence starters
        ". Clearly,", ". This is because", ". The justification is that", ". The reality is that", ". Specifically,"
    ]
};

// Phrases to introduce categories (varied)
export const CATEGORY_INTRO_PHRASES: Record<string, string[]> = {
    default: [
        "In the area of {CATEGORY}",
        "Looking specifically at {CATEGORY}",
        "My thoughts on {CATEGORY} funding include",
        "Regarding the {CATEGORY} budget",
        "Within the {CATEGORY} allocation",
        "Focusing on {CATEGORY}, I note that",
        "Turning our attention to {CATEGORY}",
    ],
    "War and Weapons": [
        "Turning to defense spending",
        "Regarding the substantial budget for {CATEGORY}",
        "My concerns about {CATEGORY} spending are",
        "Examining the allocation for {CATEGORY}",
        "With respect to our military and defense posture",
    ],
     "Health": [
        "In the critical area of {CATEGORY} funding",
        "Considering our nation's {CATEGORY} priorities",
        "With respect to the {CATEGORY} budget",
        "Analyzing expenditures in {CATEGORY}",
        "Regarding federal {CATEGORY} programs",
    ],
     "Interest on Debt": [ // Special handling - usually standalone
        "The significant amount allocated just to servicing the {CATEGORY} is deeply concerning",
        "Addressing the burden of {CATEGORY} requires immediate focus",
        "The substantial payments towards {CATEGORY} warrant specific attention",
    ],
     "Education": [
         "Focusing on federal {CATEGORY} programs",
         "Regarding investments in {CATEGORY}",
         "In the realm of {CATEGORY} policy",
         "When considering the {CATEGORY} budget",
    ],
    "Housing and Community": [
         "Turning to {CATEGORY} development",
         "Regarding federal support for {CATEGORY}",
         "In the context of {CATEGORY} programs",
         "Analyzing spending on {CATEGORY}",
    ]
    // Add more category-specific intros if desired
};

// Phrases to connect sentences *within* a category paragraph (more subtle transitions)
export const INTRA_PARAGRAPH_CONNECTORS: string[] = [
    "Additionally,",
    "Furthermore,",
    "Moreover,",
    "Similarly,",
    "In this same vein,",
    "Along these lines,",
    "Another point is that", // This starts a clause, ensure following part is lowercase
    "It's also worth noting that", // Clause starter
    "In this context,",
    "Relatedly,",
    "Correspondingly,",
    "Likewise,",
];

// Closing salutations
export const SALUTATIONS: string[] = [
    "Sincerely,", "Respectfully,", "Regards,", "Thank you for your consideration,", "Yours truly,"
];

    