import type {Metadata} from 'next';
import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"; // Import Toaster
import { ThemeProvider } from "@/components/ui/theme-provider"; // Import ThemeProvider

// Use GeistSans.variable directly
const geistSansVariable = GeistSans.variable;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Remove extra whitespace between tags
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      {/* Apply font variable and antialiased class */}
      <body className={`${geistSansVariable} font-sans antialiased`} suppressHydrationWarning>
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
         >
            {children}
            <Toaster /> {/* Add Toaster component here */}
        </ThemeProvider>
      </body>
    </html>
  );
}
