
'use client';

import * as React from 'react';
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription,
  DialogFooter, DialogClose,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { AlertTriangle, Copy, Send } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { SUBJECT } from '@/services/email/generator';
import type { Tone } from '@/services/email/types';

interface PromptTooLongModalProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  promptText: string;
  aiModelName: string;
  aiModelUrlWithoutPrompt: string;
  onEmailGenerated: () => void;
  userName: string; // Can now be empty or a placeholder
  userLocation: string; // Can now be empty or a placeholder
  tone: Tone;
}

export default function PromptTooLongModal({
  isOpen,
  onOpenChange,
  promptText,
  aiModelName,
  aiModelUrlWithoutPrompt,
  onEmailGenerated,
  userName,
  userLocation,
  tone,
}: PromptTooLongModalProps) {
  const { toast } = useToast();

  const handleCopyToClipboardAndOpen = async () => {
    try {
      await navigator.clipboard.writeText(promptText);
      toast({
        title: 'Prompt Copied!',
        description: `The prompt for ${aiModelName} has been copied to your clipboard.`,
        duration: 5000,
      });
      window.open(aiModelUrlWithoutPrompt, '_blank');
      onOpenChange(false);
      onEmailGenerated();
    } catch (err) {
      console.error('Failed to copy prompt: ', err);
      toast({
        title: 'Copy Failed',
        description: 'Could not copy the prompt. Please try again or copy manually from the console if needed.',
        variant: 'destructive',
      });
    }
  };

  const handleOpenEmailClientForPasting = () => {
    const genericSubject = SUBJECT[tone] || SUBJECT[0];
    // Use potentially placeholder values for name and location
    const finalUserName = userName.trim() === '' || userName === '[Your Name]' ? '[Your Name]' : userName;
    const finalUserLocation = userLocation.trim() === '' || userLocation === '[Your Location]' ? '[Your Location]' : userLocation;

    const placeholderBody = `Hello [Representative Name],\n\nI am writing to you today regarding federal budget priorities.\n\n[Please paste the email body generated by ${aiModelName} here.]\n\nThank you for your time and consideration.\n\nSincerely,\n${finalUserName}\n${finalUserLocation}`;
    window.location.href = `mailto:?subject=${encodeURIComponent(genericSubject)}&body=${encodeURIComponent(placeholderBody)}`;
    onOpenChange(false);
    onEmailGenerated();
  }


  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="h-full w-full max-h-none rounded-none sm:h-auto sm:w-auto sm:max-w-md sm:max-h-[90vh] sm:rounded-lg data-[state=open]:animate-scaleIn data-[state=closed]:animate-scaleOut flex flex-col">
        <DialogHeader className="text-left shrink-0 px-4 pt-4 sm:px-6 sm:pt-6">
          <DialogTitle className="flex items-center gap-2 text-lg font-semibold">
            <AlertTriangle className="h-5 w-5 text-amber-500" />
            Prompt May Be Too Long
          </DialogTitle>
          <DialogDescription className="text-sm text-muted-foreground pt-1">
            The generated prompt ({promptText.length} characters) might be too long for direct use in a URL with {aiModelName}.
            This can sometimes cause issues when opening the AI provider&apos;s website.
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto px-4 py-4 sm:px-6 space-y-3 text-sm">
            <p>
                We recommend copying the prompt and pasting it manually into <strong>{aiModelName}</strong> after it opens.
            </p>
            <p>
                Alternatively, after {aiModelName} generates the email content, you can click the button below to open your email client with a placeholder, then paste the AI-generated text there.
            </p>
        </div>

        <DialogFooter className="flex-col sm:flex-row gap-2 sm:justify-end shrink-0 px-4 pb-4 pt-2 sm:px-6 sm:pb-6 border-t bg-card/95">
          <DialogClose asChild>
            <Button type="button" variant="outline">
              Cancel
            </Button>
          </DialogClose>
          <Button type="button" onClick={handleCopyToClipboardAndOpen} className="bg-amber-500 hover:bg-amber-600 text-white">
            <Copy className="mr-2 h-4 w-4" /> Copy Prompt & Open {aiModelName}
          </Button>
           <Button type="button" onClick={handleOpenEmailClientForPasting} variant="secondary">
            <Send className="mr-2 h-4 w-4" /> Open Email Client for Pasting
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
